### PR TITLE
Fix bug causing build to hang if build.xml exists

### LINKED ISSUE #3: Builds hanging in CircleStylePlugin after upgrading to 1.1.0
Looks like the File.exists call is hanging, maybe an issue with the filesystem?

Stacktrace of the gradle daemon:
```
"Daemon worker" #29 prio=5 os_prio=0 tid=0x00007efd5c00a800 nid=0x2d11 runnable [0x00007efd72342000]
   java.lang.Thread.State: RUNNABLE
        at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
        at java.io.File.exists(File.java:819)
        at com.palantir.gradle.circlestyle.CircleStylePlugin.configureBuildFailureFinalizer(CircleStylePlugin.java:67)
        at com.palantir.gradle.circlestyle.CircleStylePlugin.apply(CircleStylePlugin.java:40)
        at com.palantir.gradle.circlestyle.CircleStylePlugin.apply(CircleStylePlugin.java:31)
```

### PR DESCRIPTION
**Pull request by alicederyn**
This causes publish steps to fail (since build.xml will obviously already have been created), and is just down to a missing increment.

This fixes #3.

### CODE REVIEW

File: src/main/java/com/palantir/gradle/circlestyle/CircleStylePlugin.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ private void configureBuildFailureFinalizer(Project rootProject, String circleRe
         int attemptNumber = 1;
         File targetFile = new File(new File(circleReportsDir, "gradle"), "build.xml");
         while (targetFile.exists()) {
-            targetFile = new File(new File(circleReportsDir, "gradle"), "build" + attemptNumber + ".xml");
+            targetFile = new File(new File(circleReportsDir, "gradle"), "build" + (++attemptNumber) + ".xml");
```
Comment (gracew) [inline src/main/java/com/palantir/gradle/circlestyle/CircleStylePlugin.java:68]: haha, nice.

File: src/main/java/com/palantir/gradle/circlestyle/CircleStylePlugin.java [hunk 2]
```diff
@@ -65,7 +65,7 @@ private void configureBuildFailureFinalizer(Project rootProject, String circleRe
         int attemptNumber = 1;
         File targetFile = new File(new File(circleReportsDir, "gradle"), "build.xml");
```
Comment (gracew) [inline src/main/java/com/palantir/gradle/circlestyle/CircleStylePlugin.java:66]: should this one be called build1.xml for symmetry?

**Review by gracew — APPROVED** [review]
lgtm

File: src/main/java/com/palantir/gradle/circlestyle/CircleStylePlugin.java (hunk 2 above)
Comment (alicederyn) [reply src/main/java/com/palantir/gradle/circlestyle/CircleStylePlugin.java:66]: I think foo.bar -> foo2.bar -> foo3.bar is standard?
